# Generated by Django 4.0.3 on 2022-04-20 20:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('routeID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('routeName', models.TextField()),
                ('routeNumber', models.TextField()),
                ('offCampus', models.BooleanField()),
                ('gameDay', models.BooleanField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stopID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('stopName', models.TextField()),
                ('waypoint', models.BooleanField(default=1)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('stopNum', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.routes')),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('timeID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.stops')),
            ],
        ),
    ]
