# Generated by Django 4.0.3 on 2022-04-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='date',
        ),
        migrations.RemoveField(
            model_name='routes',
            name='gameDay',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='waypoint',
        ),
    ]
