# Generated by Django 4.0.3 on 2022-04-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_remove_routes_date_remove_routes_gameday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='offCampus',
            field=models.TextField(),
        ),
    ]
