# Generated by Django 4.0.3 on 2022-04-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_routes_offcampus'),
    ]

    operations = [
        migrations.AddField(
            model_name='stops',
            name='stopDesc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
