# Generated by Django 4.0.3 on 2022-04-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_stops_stopdesc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routes',
            old_name='offCampus',
            new_name='area',
        ),
    ]
