# Generated by Django 4.0.3 on 2022-04-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_stops_timed'),
    ]

    operations = [
        migrations.AddField(
            model_name='stops',
            name='times',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Times',
        ),
    ]
